### ISSUE TITLE
ユーザーにロールを複数設定すると、同じユーザーが設定されたロールの数だけ表示される

### ISSUE THREAD

**Issue by tonimaru** [yuuu/redmine_nikoca_re#2]
# 概要

[プロジェクト] > 設定 > メンバー で1ユーザーに複数のロールを設定すると、カレンダーに同じユーザーがロールの数だけ表示されました。
# 期待する動作

複数ロールを設定しても1ユーザー1行で表示してほしい。
# 確認環境

```
Environment:
  Redmine version                3.0.7.stable
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
```
# 修正案

これでいいのか自信ないですが、以下のパッチで期待する動作になりました。

``` diff
diff --git a/app/controllers/niko_faces_controller.rb b/app/controllers/niko_faces_controller.rb
index 35d7155..7b8d6f6 100644
--- a/app/controllers/niko_faces_controller.rb
+++ b/app/controllers/niko_faces_controller.rb
@@ -140,10 +140,6 @@ private
   # @param project [Project] カレントプロジェクト
   # @return [Array] ユーザリスト
   def get_users(project)
-    users = Array.new
-    project.members.each do |member|
-      users << member.user
-    end
-    return users
+    return project.assignable_users
   end
 end
```

**Comment by yuuu** [comment]
対応が遅くなってしまい申し訳ありませんでした。
取り急ぎ確認したところ最新バージョンのRedmineでは現象が再現しませんでした。修正可否については原因追求後に判断しますのでしばしお待ちください。

**Comment by tonimaru** [comment]
対応ありがとうございます。
今最新の 3.2.2 を入れて試したところ、こちらでも再現しませんでした。
再度 3.0.7 にダウングレードしてみると再現したため、3.0系の不具合かもしれません。
特に大きな問題でもないため、非対応でも大丈夫です。

**Comment by yuuu** [comment]
Redmine側の以下変更が影響して3.1.4では再現しなかったようです。
https://github.com/redmine/redmine/commit/3811ff5d95bd848f457c9d29a162ce83f12fe3ac

提示いただいている修正方法にてユーザがユニークに表示できますので、反映いたしました。
https://github.com/yuuu/redmine_nikoca_re/commit/21851e8788da095f888390ad65bc084ca4f8dd09

**Comment by tonimaru** [comment]
修正ありがとうございました！
3.0.7と3.2.2でユーザーが複数表示されないことが確認できたため、Closeします。
