### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by takeshi0206** [yuuu/redmine_nikoca_re#6]
プロジェクトのユーザーにグループがエントリーされていると、以下のエラーとなるようです。

> Started GET "/redmine/projects/t-n/niko_faces" for xxx.xxx.xxx.xxx at 2016-08-23 09:35:07 +0900
> Processing by NikoFacesController#index as HTML
> Parameters: {"project_id"=>"hoge"}
> Current user: hoge_hoge (id=3)
> Rendered plugins/redmine_nikoca_re/app/views/niko_faces/_calender.html.erb (49.6ms)
> Rendered plugins/redmine_nikoca_re/app/views/niko_faces/index.html.erb within layouts/base (52.0ms)
> Completed 500 Internal Server Error in 227.3ms
> ActionView::Template::Error (undefined method `[]' for nil:NilClass):
> 42: <table class="calender">
> 43: <tr>
> 44: <% @dates.each do |date| >
> 45: <td>< link_comment_face_tag(@project, @niko_faces[user.name][date.day]) ></td>
> 46: < end %>
> 47: </tr>
> 48: </table>
> plugins/redmine_nikoca_re/app/views/niko_faces/_calender.html.erb:45:in`block (2 levels) in plugins_redmine_nikoca_re_app_views_niko_faces_calender_html_erb__449268902_104834340'

※上記のユーザー（hoge_hoge）は、グループではありません。ログインユーザー名です。

  Redmine version 2.5.2.stable
  Ruby version 1.9.3-p547 (2014-05-14) [i686-linux]
  Rails version 3.2.19

**Comment by yuuu** [comment]
遅くなりましたが調査及び修正しました。
https://github.com/yuuu/redmine_nikoca_re/commit/78a7031094aa4bc916c50401d13f31027cbf06a9

修正版を適用しなくとも以下設定を変更可能であれば応急処置できます。
・管理＞設定＞チケットトラッキング＞グループへのチケット割り当てを許可　のチェックを外す

**Comment by takeshi0206** [comment]
確認できました。ありがとうございました！
